version: '3.8'

services:


  # Database for rooms, with the entrypoint "init-rooms.sql"
  mysql-rooms:
    image: mysql:latest
    container_name: mysql-rooms
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rooms_db
    ports:
      - "3306:3306"
    volumes:
      - ./init-rooms.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - thermostat_network


  # Database for thermostats, with the entrypoint "init-thermostat.sql"
  mysql-thermostat:
    image: mysql:latest
    container_name: mysql-thermostat
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: thermostat_db
    ports:
      - "3308:3306"
    volumes:
      - ./init-thermostat.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - thermostat_network

  # Backend. Requires both the databases
  backend:
    build:
      context: ./WebServicesBackend
      dockerfile: Dockerfile
    image: backendcustom
    container_name: backend-main
    ports:
      - "50000:80"
    networks:
      - thermostat_network
    depends_on:
      - mysql-thermostat
      - mysql-rooms

  #Frontend, requires the Backend. Also the output-port is routed outside the network ("thermostat-network") to the 127.0.0.1:8080 IP and Port combo
  frontend:
    build:
      context: ./WebServicesFrontend
      dockerfile: Dockerfile
    image: frontendcustom
    container_name: frontend-main
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - thermostat_network
    depends_on:
      - backend
  
  #Here comes the thermostats. THe first is the only one thats built. In the building process it creates an image, which is used by the others. This works well enough, but sadly leads to docker showing errors when trying to build the latter 24 thermostats. Creating the containers works fine.
  #I could build 25 thermostats, but each build creates an image, which is ridiculous
  thermostat-1:
    build:
      context: ./WebServicesThermostatBackend
      dockerfile: Dockerfile
    image: thermostatcustom
    container_name: thermostat-1
    ports:
      - "50001:8080"
    networks:
      - thermostat_network

  thermostat-2:
    image: thermostatcustom
    container_name: thermostat-2
    ports:
      - "50002:8080"
    networks:
      - thermostat_network


  thermostat-3:
    image: thermostatcustom
    container_name: thermostat-3
    ports:
      - "50003:8080"
    networks:
      - thermostat_network

  thermostat-4:
    image: thermostatcustom
    container_name: thermostat-4
    ports:
      - "50004:8080"
    networks:
      - thermostat_network

  thermostat-5:
    image: thermostatcustom
    container_name: thermostat-5
    ports:
      - "50005:8080"
    networks:
      - thermostat_network

  thermostat-6:
    image: thermostatcustom
    container_name: thermostat-6
    ports:
      - "50006:8080"
    networks:
      - thermostat_network

  thermostat-7:
    image: thermostatcustom
    container_name: thermostat-7
    ports:
      - "50007:8080"
    networks:
      - thermostat_network

  thermostat-8:
    image: thermostatcustom
    container_name: thermostat-8
    ports:
      - "50008:8080"
    networks:
      - thermostat_network

  thermostat-9:
    image: thermostatcustom
    container_name: thermostat-9
    ports:
      - "50009:8080"
    networks:
      - thermostat_network

  thermostat-10:
    image: thermostatcustom
    container_name: thermostat-10
    ports:
      - "50010:8080"
    networks:
      - thermostat_network

  thermostat-11:
    image: thermostatcustom
    container_name: thermostat-11
    ports:
      - "50011:8080"
    networks:
      - thermostat_network

  thermostat-12:
    image: thermostatcustom
    container_name: thermostat-12
    ports:
      - "50012:8080"
    networks:
      - thermostat_network

  thermostat-13:
    image: thermostatcustom
    container_name: thermostat-13
    ports:
      - "50013:8080"
    networks:
      - thermostat_network

  thermostat-14:
    image: thermostatcustom
    container_name: thermostat-14
    ports:
      - "50014:8080"
    networks:
      - thermostat_network

  thermostat-15:
    image: thermostatcustom
    container_name: thermostat-15
    ports:
      - "50015:8080"
    networks:
      - thermostat_network

  thermostat-16:
    image: thermostatcustom
    container_name: thermostat-16
    ports:
      - "50016:8080"
    networks:
      - thermostat_network

  thermostat-17:
    image: thermostatcustom
    container_name: thermostat-17
    ports:
      - "50017:8080"
    networks:
      - thermostat_network

  thermostat-18:
    image: thermostatcustom
    container_name: thermostat-18
    ports:
      - "50018:8080"
    networks:
      - thermostat_network

  thermostat-19:
    image: thermostatcustom
    container_name: thermostat-19
    ports:
      - "50019:8080"
    networks:
      - thermostat_network

  thermostat-20:
    image: thermostatcustom
    container_name: thermostat-20
    ports:
      - "50020:8080"
    networks:
      - thermostat_network

  thermostat-21:
    image: thermostatcustom
    container_name: thermostat-21
    ports:
      - "50021:8080"
    networks:
      - thermostat_network

  thermostat-22:
    image: thermostatcustom
    container_name: thermostat-22
    ports:
      - "50022:8080"
    networks:
      - thermostat_network

  thermostat-23:
    image: thermostatcustom
    container_name: thermostat-23
    ports:
      - "50023:8080"
    networks:
      - thermostat_network

  thermostat-24:
    image: thermostatcustom
    container_name: thermostat-24
    ports:
      - "50024:8080"
    networks:
      - thermostat_network

  thermostat-25:
    image: thermostatcustom
    container_name: thermostat-25
    ports:
      - "50025:8080"
    networks:
      - thermostat_network


networks:
  thermostat_network:
