version: '3.8'

services:

  mysql-rooms:
    image: mysql:latest
    container_name: mysql-rooms
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rooms_db
    ports:
      - "3306:3306"
    volumes:
      - ./init-rooms.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network

  mysql-thermostat:
    image: mysql:latest
    container_name: mysql-thermostat
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: thermostat_db
    ports:
      - "3308:3306"
    volumes:
      - ./init-thermostat.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network

  
  thermostat-1:
    build:
      context: ./WebServicesThermostatBackend
      dockerfile: Dockerfile
    image: thermostatcustom
    container_name: thermostat-1
    ports:
      - "50001:8081"
    networks:
      - db_network

  thermostat-2:
    image: thermostatcustom
    container_name: thermostat-2
    ports:
      - "50002:8081"
    networks:
      - db_network


networks:
  db_network:
